INSERT INTO USER_AUTHORITIES (ID, USERNAME, AUTHORITY) VALUES (0, 'alice', 'read');
INSERT INTO USER_AUTHORITIES (ID, USERNAME, AUTHORITY) VALUES (1, 'alice', 'write');

INSERT INTO USER_AUTHORITIES (ID, USERNAME, AUTHORITY) VALUES (2, 'bob', 'read');
INSERT INTO USER_AUTHORITIES (ID, USERNAME, AUTHORITY) VALUES (3, 'bob', 'write');

INSERT INTO USER_AUTHORITIES (ID, USERNAME, AUTHORITY) VALUES (4, 'ben', 'read');
INSERT INTO USER_AUTHORITIES (ID, USERNAME, AUTHORITY) VALUES (5, 'ben', 'write');

INSERT INTO USER_AUTHORITIES (ID, USERNAME, AUTHORITY) VALUES (6, 'eva', 'read');
